# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49d61272cea2f7469feb1f159b76038dc3fe4b9f16d0dff4d6cb121099a34c5e08d149c239e1e1666efbe590d9d19fc44d2f9c5f4e7a519c3351ae152173d3d6

test:
  secret_key_base: 0fd74082b8eb274a91a5a7f5d329ec9823541b2624f06e600ea1e5ff136ede9f0c758c7230022d464d2952e6840beabda38a42a6d5d746caa5af34197d807473

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
